---
name: CI

'on':
  - push
  - pull_request

env:
  GOPROXY: https://proxy.golang.org
  GOPATH: ${{ github.workspace }}/go

permissions:
  contents: read

jobs:
  build-linux-amd64:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938
        with:
          path: ${{ env.GOPATH }}/src/k8s.io/kops

      - name: Set up go
        uses: actions/setup-go@0a12ed9d6a96ab950c8f026ed9f722fe0da7ef32
        with:
          go-version-file: '${{ env.GOPATH }}/src/k8s.io/kops/go.mod'

      - name: make all examples test
        working-directory: ${{ env.GOPATH }}/src/k8s.io/kops
        run: |
          make all examples test

  build-macos-amd64:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938
      with:
        path: ${{ env.GOPATH }}/src/k8s.io/kops

    - name: Set up go
      uses: actions/setup-go@0a12ed9d6a96ab950c8f026ed9f722fe0da7ef32
      with:
        go-version-file: '${{ env.GOPATH }}/src/k8s.io/kops/go.mod'

    - name: make kops examples test
      working-directory: ${{ env.GOPATH }}/src/k8s.io/kops
      run: |
        make kops examples test

  build-windows-amd64:
    runs-on: windows-2022
    steps:
    - uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938
      with:
        path: ${{ env.GOPATH }}/src/k8s.io/kops

    - name: Set up go
      uses: actions/setup-go@0a12ed9d6a96ab950c8f026ed9f722fe0da7ef32
      with:
        go-version-file: '${{ env.GOPATH }}/src/k8s.io/kops/go.mod'

    - name: make kops examples test
      working-directory: ${{ env.GOPATH }}/src/k8s.io/kops
      run: |
        make kops examples test-windows

  verify:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938
        with:
          path: ${{ env.GOPATH }}/src/k8s.io/kops

      - name: Set up go
        uses: actions/setup-go@0a12ed9d6a96ab950c8f026ed9f722fe0da7ef32
        with:
          go-version-file: '${{ env.GOPATH }}/src/k8s.io/kops/go.mod'

      - name: make quick-ci
        working-directory: ${{ env.GOPATH }}/src/k8s.io/kops
        run: |
          make quick-ci
